server:
  port: 8070
spring:
  application:
    name: "eurekaserver"

  #spring config server details ,where configserver is the name of config server service
  config:
    import: "optional:configserver:http://localhost:8071/"

# ****************Moving this config in Github***********************
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    fetchRegistry: false
#    registerWithEureka: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

