server:
  port: 8071
spring:
  application:
    name: "configserver"
  profiles:
    # git means we are using the git for config server ,there is another way like file system and classpath
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Yogendrachandel/spring-boot-config-server.git"
          default-label: main # if we have multiple branches in git and main is the default one
          timeout: 5    # wait only for 5 sec to connect with git hub
          clone-on-start: true # clone the git hub values on start up of this service
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true



