package com.learn.entity;


import lombok.*;

import jakarta.persistence.*;


@Entity
@Getter
@Setter
@ToString
@AllArgsConstructor
@NoArgsConstructor
//here we dont use the Table annonation because our class name is exactly same as Db table name,no need
public class Accounts extends  BaseEntity {

    //from customer table
    @Column(name="customer_id")
    private Long customerId;

    //here account_number generated from our logic  , so no autogenerated
    @Column(name="account_number")
    @Id
    private Long accountNumber;

    @Column(name="account_type")
    private String accountType;

    @Column(name="branch_address")
    private String branchAddress;

}